// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziubgqkpehhguzxtxies.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppdWJncWtwZWhoZ3V6eHR4aWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTUzNjgsImV4cCI6MjA2Mzk5MTM2OH0.oR-5rKB9_RsEJ91YzaLJzAeEDytwgqHx2M1DesQydjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);